version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php_app
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    ports:
      - "9001:9000"
    environment:
      - APP_ENV=dev
    depends_on:
      - database
      - redis
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
      - database
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: symfony_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  redis_data:
###< doctrine/doctrine-bundle ###
networks:
  app-network:
    driver: bridge